package pojo;
// Generated Mar 29, 2011 10:22:08 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Entitybase generated by hbm2java
 */
@Entity
@Table(name="entitybase"
    ,catalog="entitydb"
)
public class Entitybase  implements java.io.Serializable {

     private User owner ;
     private String entityId;
     private Integer entityTypeId;
     private String entityAccessStatus;
     private String entityParentEdit;
     private String ownerId;
     private Set peoples = new HashSet(0);
     private Set events = new HashSet(0);

    public Entitybase() {
    }

	
    public Entitybase(String entityId) {
        this.entityId = entityId;
    }
    public Entitybase(String entityId, Integer entityTypeId, String entityAccessStatus, String entityParentEdit, String ownerId, Set peoples, Set events) {
       this.entityId = entityId;
       this.entityTypeId = entityTypeId;
       this.entityAccessStatus = entityAccessStatus;
       this.entityParentEdit = entityParentEdit;
       this.ownerId = ownerId;
       this.peoples = peoples;
       this.events = events;
    }
   
     @Id 
    
    @Column(name="EntityID", unique=true, nullable=false, length=40)
    public String getEntityId() {
        return this.entityId;
    }
    
    public void setEntityId(String entityId) {
        this.entityId = entityId;
    }
    
    @Column(name="EntityTypeID")
    public Integer getEntityTypeId() {
        return this.entityTypeId;
    }
    
    public void setEntityTypeId(Integer entityTypeId) {
        this.entityTypeId = entityTypeId;
    }
    
    @Column(name="EntityAccessStatus", length=20)
    public String getEntityAccessStatus() {
        return this.entityAccessStatus;
    }
    
    public void setEntityAccessStatus(String entityAccessStatus) {
        this.entityAccessStatus = entityAccessStatus;
    }
    
    @Column(name="EntityParentEdit", length=20)
    public String getEntityParentEdit() {
        return this.entityParentEdit;
    }
    
    public void setEntityParentEdit(String entityParentEdit) {
        this.entityParentEdit = entityParentEdit;
    }
    
    @Column(name="OwnerID", length=40)
    public String getOwnerId() {
        return this.ownerId;
    }
    public void setOwner(User owner) {
        System.out.println("######################### EntityBase.setOwner() ") ;
        this.owner = owner;
    }
    public void setOwnerId(String ownerId) {
        this.ownerId = ownerId;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="entitybase")
    public Set getPeoples() {
        return this.peoples;
    }
    
    public void setPeoples(Set peoples) {
        this.peoples = peoples;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="entitybase")
    public Set getEvents() {
        return this.events;
    }
    
    public void setEvents(Set events) {
        this.events = events;
    }




}


