package pojo;
// Generated Mar 29, 2011 10:22:08 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * People generated by hbm2java
 */
@Entity
@Table(name="people"
    ,catalog="entitydb"
)
public class Person extends Entitybase implements java.io.Serializable {


     private String entityId;
     private Entitybase entitybase;
     private String peopleFirstName;
     private String peopleLastName;
     private String peopleEmail;
     private String peoplePhone;
     private Set userses = new HashSet(0);

    public Person() {
    }

	
    public Person(String entityId, Entitybase entitybase) {
        this.entityId = entityId;
        this.entitybase = entitybase;
    }
    public Person(String entityId, Entitybase entitybase, String peopleFirstName, String peopleLastName, String peopleEmail, String peoplePhone, Set userses) {
       this.entityId = entityId;
       this.entitybase = entitybase;
       this.peopleFirstName = peopleFirstName;
       this.peopleLastName = peopleLastName;
       this.peopleEmail = peopleEmail;
       this.peoplePhone = peoplePhone;
       this.userses = userses;
    }
   
     @Id 
    
    @Column(name="EntityID", unique=true, nullable=false, length=40)
    public String getEntityId() {
        return this.entityId;
    }
    
    public void setEntityId(String entityId) {
        this.entityId = entityId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EntityID", unique=true, nullable=false, insertable=false, updatable=false)
    public Entitybase getEntitybase() {
        return this.entitybase;
    }
    
    public void setEntitybase(Entitybase entitybase) {
        this.entitybase = entitybase;
    }
    
    @Column(name="PeopleFirstName", length=50)
    public String getPeopleFirstName() {
        return this.peopleFirstName;
    }
    
    public void setPeopleFirstName(String peopleFirstName) {
        this.peopleFirstName = peopleFirstName;
    }
    
    @Column(name="PeopleLastName", length=50)
    public String getPeopleLastName() {
        return this.peopleLastName;
    }
    
    public void setPeopleLastName(String peopleLastName) {
        this.peopleLastName = peopleLastName;
    }
    
    @Column(name="PeopleEmail", length=100)
    public String getPeopleEmail() {
        return this.peopleEmail;
    }
    
    public void setPeopleEmail(String peopleEmail) {
        this.peopleEmail = peopleEmail;
    }
    
    @Column(name="PeoplePhone", length=20)
    public String getPeoplePhone() {
        return this.peoplePhone;
    }
    
    public void setPeoplePhone(String peoplePhone) {
        this.peoplePhone = peoplePhone;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="people")
    public Set getUserses() {
        return this.userses;
    }
    
    public void setUserses(Set userses) {
        this.userses = userses;
    }




}


