package pojo;
// Generated Mar 29, 2011 10:22:08 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users"
    ,catalog="entitydb"
)
public class User extends Person  implements java.io.Serializable {


     private String entityId;
     private Person people;
     private String userEmail;
     private String userSalt;
     private String userPasswordHash;
     private String userOauthToken;

    public User() {
        setOwner(this);
    }

	
    public User(String entityId, Person people) {
        this.entityId = entityId;
        this.people = people;
    }
    public User(String entityId, Person people, String userEmail, String userSalt, String userPasswordHash, String userOauthToken) {
       this.entityId = entityId;
       this.people = people;
       this.userEmail = userEmail;
       this.userSalt = userSalt;
       this.userPasswordHash = userPasswordHash;
       this.userOauthToken = userOauthToken;
    }
   
     @Id 
    
    @Column(name="EntityID", unique=true, nullable=false, length=40)
    public String getEntityId() {
        return this.entityId;
    }
    
    public void setEntityId(String entityId) {
        this.entityId = entityId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EntityID", unique=true, nullable=false, insertable=false, updatable=false)
    public Person getPeople() {
        return this.people;
    }
    
    public void setPeople(Person people) {
        this.people = people;
    }
    
    @Column(name="UserEmail", length=100)
    public String getUserEmail() {
        return this.userEmail;
    }
    
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }
    
    @Column(name="UserSalt", length=20)
    public String getUserSalt() {
        return this.userSalt;
    }
    
    public void setUserSalt(String userSalt) {
        this.userSalt = userSalt;
    }
    
    @Column(name="UserPasswordHash", length=64)
    public String getUserPasswordHash() {
        return this.userPasswordHash;
    }
    
    public void setUserPasswordHash(String userPasswordHash) {
        this.userPasswordHash = userPasswordHash;
    }
    
    @Column(name="UserOauthToken", length=20)
    public String getUserOauthToken() {
        return this.userOauthToken;
    }
    
    public void setUserOauthToken(String userOauthToken) {
        this.userOauthToken = userOauthToken;
    }




}


